spring:
  application:
    name: rihua-api
  
  profiles:
    active: dev
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Tokyo
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    encoding: UTF-8
  
  # Redis Configuration
  data:
    redis:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Tokyo
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  
  # Internationalization
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  
  # Servlet Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  error:
    include-stacktrace: never
    include-message: always

# Management Configuration (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    jp.co.protosoft.rihua.api: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: Rihua Community Platform API
    description: REST API for Rihua Community Platform
    version: 1.0.0
    contact:
      name: Rihua Development Team
      email: dev@rihua.com

# Application Specific Configuration
rihua:
  jwt:
    secret: ${JWT_SECRET:rihua-jwt-secret-key-change-in-production}
    access-token-expiration: 3600000 # 1 hour
    refresh-token-expiration: 2592000000 # 30 days
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  file:
    upload:
      max-size: 10MB
      allowed-types: image/jpeg,image/png,image/gif,application/pdf
  
  pagination:
    default-page-size: 20
    max-page-size: 100